const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //admin
    SAVE_USER: 'SAVE_USER',
    CLEAR_USER: 'CLEAR_USER',
    FETCH_CAMPAIGN: 'FETCH_CAMPAIGN',
    FETCH_HEADER: 'FETCH_HEADER',
    FETCH_MENU: 'FETCH_MENU',
    FETCH_MENUITEM: 'FETCH_MENUITEM',
    FETCH_SUBMENU: 'FETCH_SUBMENU',
    FETCH_BANNER: 'FETCH_BANNER',
    FETCH_BODY: 'FETCH_BODY',
    FETCH_FORM: 'FETCH_FORM',
    FETCH_FOOTER: 'FETCH_FOOTER',
    FETCH_FOOTER_TEXT: 'FETCH_FOOTER_TEXT',
    FETCH_FORM_DETAIL_BY_FORM: 'FETCH_FORM_DETAIL_BY_FORM',
    FETCH_INPUT: 'FETCH_INPUT',
    FETCH_PROMOTION: 'FETCH_PROMOTION',
    FETCH_PACK: 'FETCH_PACK',
})

export default actionTypes;