const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //admin
    FETCH_MENU: 'FETCH_MENU',
    FETCH_MENU_SUCCESS: 'FETCH_MENU_SUCCESS',

    FETCH_MENUITEM: 'FETCH_MENUITEM'
})

export default actionTypes;